project_id = "promrhlttjogqgevangf"

[functions.fetch-satellite-data]
verify_jwt = false

[functions.fetch-weather-data]
verify_jwt = false

[functions.run-pipeline]
verify_jwt = false

[functions.interpret-data]
verify_jwt = false

[functions.ai-agent-chat]
verify_jwt = false

[functions.upload-satellite-data]
verify_jwt = false

[functions.store-satellite-data]
verify_jwt = false

[functions.get-optimal-crop-conditions]
verify_jwt = false

[functions.analyze-field-conditions]
verify_jwt = false